// Test data for development
export const matchups = [
  // Basketball matchups
  {
    "sport": "basketball",
    "winner": "UNC",
    "loser": "Duke",
    "winner_rank": "",
    "loser_rank": "1",
    "date": "2025-09-12",
    "upset_score": 1.4,
    "impact_score": 1.5,
    "excitement_score": 1.3,
    "overall_discussion": "The ultimate rivalry game that transcends rankings. When UNC beats Duke, especially when Duke is #1, it's not just a game - it's history. The energy in the Dean Dome would be electric.",
    "upset_rationale": "Duke was ranked #1 in the nation, making this a massive upset. UNC was unranked, creating the perfect storm for court storming.",
    "impact_rationale": "This game has national implications for both programs and affects the entire college basketball landscape. Beating the #1 team always creates waves.",
    "excitement_rationale": "The Duke-UNC rivalry is legendary. The intensity, the history, and the pure hatred between these programs makes every game must-watch TV."
  },
  {
    "sport": "basketball",
    "winner": "Kentucky",
    "loser": "Louisville",
    "winner_rank": "8",
    "loser_rank": "",
    "date": "2025-01-15",
    "upset_score": 0.0,
    "impact_score": 0.25,
    "excitement_score": 1.0,
    "overall_discussion": "Kentucky-Louisville is always intense, but this was more of a routine win for the Wildcats. Not much court storming potential here.",
    "upset_rationale": "No upset here - Kentucky was ranked #8 and Louisville was unranked. This was expected.",
    "impact_rationale": "Minimal impact. Kentucky beating an unranked Louisville doesn't move the needle much nationally.",
    "excitement_rationale": "The rivalry still brings energy, but without the upset factor, it's just another rivalry game."
  },
  {
    "sport": "basketball",
    "winner": "Ohio State",
    "loser": "Michigan",
    "winner_rank": "12",
    "loser_rank": "2",
    "date": "2025-02-08",
    "upset_score": 1.0,
    "impact_score": 1.0,
    "excitement_score": 0.5,
    "overall_discussion": "The Game in basketball form. Ohio State beating Michigan always feels good, especially when Michigan is ranked higher.",
    "upset_rationale": "Michigan was ranked #5 while Ohio State was #12, making this a solid upset victory for the Buckeyes.",
    "impact_rationale": "Huge impact on the Big Ten standings and NCAA tournament seeding. This game matters for both teams' postseason hopes.",
    "excitement_rationale": "The Ohio State-Michigan rivalry transcends sports. The intensity and hatred between these programs is unmatched."
  },
  {
    "sport": "basketball",
    "winner": "Alabama",
    "loser": "Auburn",
    "winner_rank": "3",
    "loser_rank": "15",
    "date": "2025-01-22",
    "upset_score": 1.0,
    "impact_score": 1.4,
    "excitement_score": 1.2,
    "overall_discussion": "The Iron Bowl of basketball. Alabama's victory over Auburn in this heated rivalry always generates excitement.",
    "upset_rationale": "Auburn was ranked #15 while Alabama was #3, so this was a significant upset for the Tigers.",
    "impact_rationale": "Major implications for SEC standings and tournament seeding. This rivalry game always has postseason consequences.",
    "excitement_rationale": "The Alabama-Auburn rivalry is intense in every sport. The basketball version carries the same passion and energy."
  },
  {
    "sport": "basketball",
    "winner": "Gonzaga",
    "loser": "Saint Mary's",
    "winner_rank": "7",
    "loser_rank": "22",
    "date": "2025-02-14",
    "upset_score": 0.8,
    "impact_score": 1.1,
    "excitement_score": 1.0,
    "overall_discussion": "West Coast Conference rivalry with some upset potential. Gonzaga's win over Saint Mary's was solid but not spectacular.",
    "upset_rationale": "Saint Mary's was ranked #22 while Gonzaga was #7, making this a moderate upset for the Gaels.",
    "impact_rationale": "Important for WCC standings and NCAA tournament positioning. Both teams are usually in the mix for March Madness.",
    "excitement_rationale": "The Gonzaga-Saint Mary's rivalry has grown in recent years, creating more excitement around these matchups."
  },
  {
    "sport": "basketball",
    "winner": "Georgetown",
    "loser": "Villanova",
    "winner_rank": "",
    "loser_rank": "18",
    "date": "2025-01-28",
    "upset_score": 0.6,
    "impact_score": 0.9,
    "excitement_score": 0.8,
    "overall_discussion": "Georgetown's upset of Villanova shows the Hoyas are still capable of pulling off surprises in the Big East.",
    "upset_rationale": "Villanova was ranked #18 while Georgetown was unranked, making this a solid upset for the Hoyas.",
    "impact_rationale": "Moderate impact on Big East standings. Georgetown's program has been rebuilding, so this win helps their credibility.",
    "excitement_rationale": "The Georgetown-Villanova rivalry has historical significance, though it's not as intense as it once was."
  },
  {
    "sport": "basketball",
    "winner": "Kansas",
    "loser": "Kansas State",
    "winner_rank": "4",
    "loser_rank": "",
    "date": "2025-02-01",
    "upset_score": 0.7,
    "impact_score": 1.2,
    "excitement_score": 1.0,
    "overall_discussion": "The Sunflower Showdown always brings energy, but Kansas beating Kansas State is usually expected.",
    "upset_rationale": "Kansas was ranked #4 while Kansas State was unranked, so this was expected rather than an upset.",
    "impact_rationale": "Important for Big 12 standings and Kansas's tournament seeding, but not a game-changer nationally.",
    "excitement_rationale": "The Kansas-Kansas State rivalry is intense and always brings out passionate fans on both sides."
  },
  {
    "sport": "basketball",
    "winner": "UCLA",
    "loser": "USC",
    "winner_rank": "9",
    "loser_rank": "14",
    "date": "2025-01-18",
    "upset_score": 0.9,
    "impact_score": 1.3,
    "excitement_score": 1.1,
    "overall_discussion": "The Crosstown Showdown in basketball. UCLA's victory over USC adds another chapter to this storied rivalry.",
    "upset_rationale": "USC was ranked #14 while UCLA was #9, making this a moderate upset for the Trojans.",
    "impact_rationale": "Significant for Pac-12 standings and tournament positioning. Both teams are usually competitive in the conference.",
    "excitement_rationale": "The UCLA-USC rivalry is legendary across all sports. The basketball version carries the same intensity and passion."
  },
  {
    "sport": "basketball",
    "winner": "Texas",
    "loser": "Texas A&M",
    "winner_rank": "11",
    "loser_rank": "",
    "date": "2025-02-05",
    "upset_score": 0.8,
    "impact_score": 1.1,
    "excitement_score": 0.9,
    "overall_discussion": "The Lone Star Showdown in basketball. Texas's win over Texas A&M continues their recent dominance in this rivalry.",
    "upset_rationale": "Texas was ranked #11 while Texas A&M was unranked, so this was expected rather than an upset.",
    "impact_rationale": "Important for conference standings, but Texas A&M's unranked status limits the national impact.",
    "excitement_rationale": "The Texas-Texas A&M rivalry is intense, though the basketball version doesn't quite match the football intensity."
  },
  // Football matchups
  {
    "sport": "football",
    "winner": "Auburn",
    "loser": "Alabama",
    "winner_rank": "",
    "loser_rank": "2",
    "date": "2025-11-30",
    "upset_score": 1.3,
    "impact_score": 1.5,
    "excitement_score": 1.4,
    "overall_discussion": "The Iron Bowl upset of the century. Auburn beating Alabama when the Tide was ranked #2 is the stuff of legends. This would be an all-time field storming moment.",
    "upset_rationale": "Alabama was ranked #2 in the nation while Auburn was unranked, making this one of the biggest upsets in Iron Bowl history.",
    "impact_rationale": "Massive impact on the SEC West race, College Football Playoff picture, and national championship implications. This game changes everything.",
    "excitement_rationale": "The Iron Bowl is already the most intense rivalry in college football. An upset of this magnitude would create pandemonium."
  },
  {
    "sport": "football",
    "winner": "Michigan",
    "loser": "Ohio State",
    "winner_rank": "1",
    "loser_rank": "3",
    "date": "2025-11-29",
    "upset_score": 1.4,
    "impact_score": 1.5,
    "excitement_score": 1.4,
    "overall_discussion": "The Game lived up to its billing. Michigan's victory over Ohio State in this top-3 matchup was everything college football should be.",
    "upset_rationale": "Ohio State was ranked #3 while Michigan was #1, so this was expected but still intense given the rivalry.",
    "impact_rationale": "Huge implications for the Big Ten Championship, College Football Playoff, and national championship race.",
    "excitement_rationale": "The Game is the ultimate rivalry in college football. The intensity, hatred, and passion between these programs is unmatched."
  },
  {
    "sport": "football",
    "winner": "Georgia",
    "loser": "Florida",
    "winner_rank": "4",
    "loser_rank": "16",
    "date": "2025-10-25",
    "upset_score": 1.2,
    "impact_score": 1.4,
    "excitement_score": 1.3,
    "overall_discussion": "The World's Largest Outdoor Cocktail Party delivered another classic. Georgia's victory over Florida continues their recent dominance.",
    "upset_rationale": "Florida was ranked #16 while Georgia was #4, making this a significant upset for the Gators.",
    "impact_rationale": "Major implications for the SEC East race and College Football Playoff positioning. This rivalry game always matters.",
    "excitement_rationale": "The Georgia-Florida rivalry is legendary, with the neutral site in Jacksonville adding to the unique atmosphere."
  },
  {
    "sport": "football",
    "winner": "Oklahoma",
    "loser": "Texas",
    "winner_rank": "6",
    "loser_rank": "9",
    "date": "2025-10-11",
    "upset_score": 1.1,
    "impact_score": 1.4,
    "excitement_score": 1.3,
    "overall_discussion": "The Red River Showdown delivered another thrilling chapter. Oklahoma's victory over Texas in this heated rivalry was electric.",
    "upset_rationale": "Texas was ranked #9 while Oklahoma was #6, making this a moderate upset for the Longhorns.",
    "impact_rationale": "Significant impact on the Big 12 race and College Football Playoff positioning. This game always has postseason implications.",
    "excitement_rationale": "The Red River Showdown is one of college football's greatest rivalries, with the Cotton Bowl atmosphere adding to the intensity."
  },
  {
    "sport": "football",
    "winner": "Alabama",
    "loser": "LSU",
    "winner_rank": "2",
    "loser_rank": "7",
    "date": "2025-11-08",
    "upset_score": 1.1,
    "impact_score": 1.5,
    "excitement_score": 1.2,
    "overall_discussion": "The Alabama-LSU rivalry continues to produce classics. Alabama's victory over LSU in this top-10 matchup was intense.",
    "upset_rationale": "LSU was ranked #7 while Alabama was #2, making this a solid upset for the Tigers.",
    "impact_rationale": "Huge implications for the SEC West race and College Football Playoff. This game often decides the division.",
    "excitement_rationale": "The Alabama-LSU rivalry has grown into one of the SEC's most intense, with both programs consistently competing for championships."
  },
  {
    "sport": "football",
    "winner": "Ohio State",
    "loser": "Penn State",
    "winner_rank": "3",
    "loser_rank": "12",
    "date": "2025-10-18",
    "upset_score": 1.0,
    "impact_score": 1.3,
    "excitement_score": 1.2,
    "overall_discussion": "The White Out game delivered another thriller. Ohio State's victory over Penn State in Happy Valley was a classic.",
    "upset_rationale": "Penn State was ranked #12 while Ohio State was #3, making this a significant upset for the Nittany Lions.",
    "impact_rationale": "Major implications for the Big Ten East race and College Football Playoff positioning. This game often decides the division.",
    "excitement_rationale": "The White Out atmosphere in Happy Valley is legendary, making this one of the most exciting games of the season."
  },
  {
    "sport": "football",
    "winner": "Clemson",
    "loser": "South Carolina",
    "winner_rank": "8",
    "loser_rank": "",
    "date": "2025-11-29",
    "upset_score": 0.9,
    "impact_score": 1.2,
    "excitement_score": 1.1,
    "overall_discussion": "The Palmetto Bowl continues Clemson's recent dominance. Clemson's victory over South Carolina was solid but expected.",
    "upset_rationale": "Clemson was ranked #8 while South Carolina was unranked, so this was expected rather than an upset.",
    "impact_rationale": "Important for Clemson's College Football Playoff hopes and ACC standing, but limited national impact.",
    "excitement_rationale": "The Clemson-South Carolina rivalry is intense, though Clemson's recent dominance has reduced some of the excitement."
  },
  {
    "sport": "football",
    "winner": "Washington",
    "loser": "Oregon",
    "winner_rank": "5",
    "loser_rank": "11",
    "date": "2025-10-04",
    "upset_score": 0.9,
    "impact_score": 1.2,
    "excitement_score": 1.1,
    "overall_discussion": "The Pacific Northwest rivalry delivered another classic. Washington's victory over Oregon was hard-fought and intense.",
    "upset_rationale": "Oregon was ranked #11 while Washington was #5, making this a moderate upset for the Ducks.",
    "impact_rationale": "Significant for Pac-12 standings and College Football Playoff positioning. This game often decides the conference race.",
    "excitement_rationale": "The Washington-Oregon rivalry has grown in intensity, with both programs competing for Pac-12 supremacy."
  },
  {
    "sport": "football",
    "winner": "Georgia Tech",
    "loser": "Clemson",
    "winner_rank": "12",
    "loser_rank": "",
    "date": "2025-09-13",
    "upset_score": 0.25,
    "impact_score": 0.75,
    "excitement_score": 1.0,
    "overall_discussion": "This one was close, but was missing the key ingredient of a real underdog really upsetting a real favorite.",
    "upset_rationale": "Yes, Clemson was ranked, but they were only 3 point favorites at kickoff and only 2 spots ahead of Georgia Tech in the FPI. Georgia Tech is a good team who beat a slightly better team.",
    "impact_rationale": "There is a bit of a rivalry here since the schools are only 100 miles apart and play every year. Clemson has won the last 9 meetings, and really needed a win to convince the world that they're one of the big boys. ",
    "excitement_rationale": "Georgia Tech was ahead for the whole game, then Clemson tied it up with 3 minutes to go. Tech drove to midfield, drained the clock, sprinted the field goal team on with a running clock, and hit a 55 yarder to win as time expired."
  }
];

// Legacy exports for backward compatibility
export const basketballMatchups = matchups.filter(matchup => matchup.sport === 'basketball');
export const footballMatchups = matchups.filter(matchup => matchup.sport === 'football');
export const testMatchups = basketballMatchups;
